name: canary
id: 'ari:cloud:compass:89436501-45fd-498f-9c7c-b0db10b968cb:component/d819e7ce-7ec1-48ae-b718-cb3459fc6e06/41e70807-ff9f-4225-8e75-83c73d405ad6'
slug: canary
description: 'Creator, Manager and Manager of Agent Prompts and Canary Tokens in Agent Repositories'
configVersion: 1
typeId: APPLICATION
ownerId: 'ari:cloud:identity::team/ed895264-a5df-48d6-9aa2-f44fe1686317'
fields:
  lifecycle: Active
  tier: 2
  isMonorepoProject: false
links:
  - name: null
    type: REPOSITORY
    url: 'https://github.com/devnw/canary'
  - name: 'DOCUMENTATION'
    type: WEBSITE
    url: 'https://canary.devnw.dev/'
  - name: ''
    type: PROJECT
    url: 'https://devnw.atlassian.net/browse/DEV'
  - name: Slack
    type: CHAT_CHANNEL
    url: 'https://codeprosorg.slack.com/archives/C09MCUT88MS'
relationships: {}
labels:
  - 'source:github'
  - synced-with-jsm
customFields: null
