package main

// CANARY: REQ=CBIN-103; FEATURE="StatusJSON"; ASPECT=API; STATUS=IMPL; TEST=TestCANARY_CBIN_103_API_StatusSchema; BENCH=BenchmarkCANARY_CBIN_103_API_Emit; OWNER=canary; UPDATED=2025-09-20
