# CANARY Project Configuration
# This file defines project-specific settings for requirement tracking

# Project identification
project:
  name: "canary"
  description: "CANARY requirement tracking system"

# Requirement ID pattern for this project
# This filters which CANARY tokens are considered "real" vs examples/tests
requirements:
  # Regex pattern for valid requirement IDs in this project
  # Examples:
  #   - "CBIN-[1-9][0-9]{2,}" matches CBIN-100 and above
  #   - "PROJ-.*" matches any PROJ- prefix
  #   - "CBIN-(104|105|1[1-3][0-9])" matches specific ranges
  id_pattern: "CBIN-1[0-4][0-9]"  # CBIN-100 through CBIN-149 (this project)

  # Alternative: explicit ranges
  # id_ranges:
  #   - "CBIN-104:CBIN-131"  # Inclusive range

  # Alternative: exclude patterns (for examples/tests)
  # exclude_patterns:
  #   - "CBIN-00[1-9]"  # Exclude CBIN-001 through CBIN-009 (examples)

# Scanner behavior
scanner:
  # Paths to exclude from scanning (in addition to default skip patterns)
  exclude_paths:
    - "testdata/"
    - "fixtures/"
    - "examples/"

  # File patterns to include (defaults to *.go, *.py, etc.)
  # include_patterns:
  #   - "*.go"
  #   - "*.md"

# Verification settings
verification:
  # Require TEST= field for TESTED status
  require_test_field: true

  # Require BENCH= field for BENCHED status
  require_bench_field: true

  # Staleness threshold in days (for --strict mode)
  staleness_days: 30
