# CANARY Project Configuration
# This file defines project-specific settings for requirement tracking

# Project identification
project:
  name: "canary"
  description: "CANARY requirement tracking system with spec-kit workflows"

# Requirement ID pattern for this project
# This filters which CANARY tokens are considered "real" vs examples/tests
requirements:
  # Regex pattern for valid requirement IDs in this project
  # Examples:
  #   - "CBIN-[1-9][0-9]{2,}" matches CBIN-100 and above
  #   - "CBIN-.*" matches any CBIN- prefix
  #   - "CBIN-(10[0-9]|1[1-5][0-9])" matches CBIN-100 through CBIN-159
  id_pattern: "CBIN-[1-9][0-9]{2,}"  # CBIN-100 and above (excludes example IDs 001-099)

  # Alternative: explicit ranges
  # id_ranges:
  #   - "{{PROJECT_KEY}}-100:{{PROJECT_KEY}}-999"  # Inclusive range

  # Alternative: exclude patterns (for examples/tests)
  # exclude_patterns:
  #   - "{{PROJECT_KEY}}-0[0-9]{2}"  # Exclude {{PROJECT_KEY}}-001 through {{PROJECT_KEY}}-099 (examples)

# Scanner behavior
scanner:
  # Paths to exclude from scanning (in addition to default skip patterns)
  exclude_paths:
    - "testdata/"
    - "fixtures/"
    - "examples/"
    - ".canary/templates/"
    - "specs/spec-kit-repo/"
    - "FINAL_SUMMARY.md"
    - "IMPLEMENTATION_SUMMARY_STORAGE.md"

  # File patterns to include (defaults to *.go, *.py, *.md, etc.)
  # include_patterns:
  #   - "*.go"
  #   - "*.md"
  #   - "*.py"

# Verification settings
verification:
  # Require TEST= field for TESTED status
  require_test_field: true

  # Require BENCH= field for BENCHED status
  require_bench_field: true

  # Staleness threshold in days (for --strict mode)
  staleness_days: 30
