name: Build

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  packages: write
  pages: write

jobs:
  build:
    uses: devnw/workflows/.github/workflows/make-ci.yml@main
    secrets: inherit # pragma: allowlist secret
