name: canary
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Build scanner
        run: go build -o ./bin/canary ./cmd/canary
      - name: Generate status
        run: ./bin/canary scan --root . --out status.json --csv status.csv
      - name: Self-verify
        run: ./bin/canary verify --root . --gap docs/GAP_ANALYSIS.md --strict || true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: canary-status
          path: |
            status.json
            status.csv
