name: 'Package Docs, Benchmarks, Coverage & Metrics to GitHub Pages'

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.GIT_CREDENTIALS}}

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          upstream-cache: https://spyder.cachix.org
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: spyder
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Use doc-pages composite action
        uses: codeprosorg/doc-pages@main
        id: docs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_benchmarks: true
          bench_branch: bench-data
          site_name: '${{ github.repository }} — Documentation Site'
          extra_nav_docs: true
          nav_order: home,reference,coverage,metrics,security,bench,docs
          embed_coverage_html: true
      - name: Upload doc-pages artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ${{ steps.docs.outputs.site_dir }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
