name: Lint and Guards

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run guard checks (import allowlist, doc comments)
        run: |
          go run ./tools/importguard
          go run ./tools/doccheck

      - name: go vet
        run: go vet ./...
